#!/usr/bin/env bash
# Displays Best School 10 times but at 9th display b..s then HI

COUNTER=1
while [ $COUNTER -lt 10 ] 
do
    if [ $COUNTER -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    fi 
    echo "Best School"
    ((COUNTER++))
done
