#!/usr/bin/env bash
# Displays time for 12hrs and 49 minutes

Hours=0
minutes=1
while [ $Hours -le 12 ]
do
    echo "Hour: $Hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo $minutes
        let minutes+=1
    done
    let Hours+=1
done
