#!/usr/bin/env bash
# Displays time for 12hrs and 49 minutes

Hours=0
minutes=1
while [ $Hours -le 12 ]
do
    echo "Hour: $Hours"
    while [ $minutes -le 59 ]
    do
         echo $minutes
         ((minutes++))
    done
    minutes=1
    ((Hours++))
done
